# This is a Makefile that needs a specific configuration that we
# may find at => https://sagiegurari.github.io/cargo-make/
#
# In order to run a specific you have to run a `makers <name_of_your_task>``

[tasks.dev]
command = "cargo"
args = ["watch", "-x", "run"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["clean"]

[tasks.run]
script = "cargo run"

[tasks.testing]
command = "cargo"
args = ["test"]
dependencies = ["run"]