version: '3'

services:
  postgres:
    container_name: postgres_db
    image: 'postgres:latest'
    restart: always
    volumes:
      - './postgres_data:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: demo
    ports:
      - '5432:5432'